[technote]
id = "SITCOMTN-164"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-164.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-164"
github_default_branch = "main"
date_created = 2025-06-30T15:40:53Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Xiangchong"
name.family = "Li"
internal_id = "lix2"
orcid = "https://orcid.org/0000-0003-2880-5102"
[[technote.authors.affiliations]]
name = "Brookhaven National Laboratory"
internal_id = "BNL"
address = "Upton, NY 11973, USA"
