[technote]
id = "SITCOMTN-164"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-164.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-164"
github_default_branch = "main"
date_created = 2025-06-30T15:40:53Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[bibliography]
files = ["_bibliography/references.bib"]

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Xiangchong"
name.family = "Li"
internal_id = "lix2"
orcid = "https://orcid.org/0000-0003-2880-5102"
[[technote.authors.affiliations]]
name = "Brookhaven National Laboratory"
internal_id = "BNL"
address = "Upton, NY 11973, USA"

[[technote.authors]]
name.given = "Prakruth"
name.family = "Adari"
internal_id = "adarip"
orcid = "https://orcid.org/0000-0001-9431-3806"
[[technote.authors.affiliations]]
name = "Stony Brook University"
internal_id = "StonyBrookU"
address = "Stony Brook University, Stony Brook, NY 11794, USA"
ror = "https://ror.org/05qghxh33"

[[technote.authors]]
internal_id = "lindena"
orcid = "https://orcid.org/0000-0002-3881-7724"
name = {given = "Anja", family = "von der Linden"}
[[technote.authors.affiliations]]
name = "Stony Brook University"
internal_id = "StonyBrookU"
address = "Stony Brook University, Stony Brook, NY 11794, USA"
ror = "https://ror.org/05qghxh33"

[[technote.authors]]
internal_id = "mandelbaumr"
orcid = "https://orcid.org/0000-0003-2271-1527"
name = {given = "Rachel", family = "Mandelbaum"}
[[technote.authors.affiliations]]
name = "Carnegie Mellon University"
internal_id = "CMU"
address = "Carnegie Mellon University, Pittsburgh, PA 15213, USA"
ror = "https://ror.org/05x2bcf33"
